### BASICO

importa libre y datos

In [1]:
import pandas as pd 

datos = {
    'Producto': ['Laptop', 'Teclado', 'Laptop', 'Monitor', 'Teclado', 'Mouse', 'Monitor', 'Laptop'],
    'Categoria': ['Electrónica', 'Accesorios', 'Electrónica', 'Electrónica', 'Accesorios', 'Accesorios', 'Electrónica', 'Electrónica'],
    'Region': ['Norte', 'Sur', 'Norte', 'Este', 'Sur', 'Norte', 'Este', 'Sur'],
    'Precio_Unitario': [1200, 45, 1100, 300, 50, 25, 320, 1250],
    'Cantidad': [2, 10, 1, 4, 12, 60, 2, 9],
    'Sueldo': [4500, 3200, 6000, 2800, 5200, 1900, 4100, 7500]
}

df = pd.DataFrame(datos)

In [2]:
df['Region']

0    Norte
1      Sur
2    Norte
3     Este
4      Sur
5    Norte
6     Este
7      Sur
Name: Region, dtype: str

In [ ]:
# Decir las columnas que clase de datos tienen, y cuantos valor NO-NULL tienen
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Producto         8 non-null      str
 1   Categoria        8 non-null      str
 2   Region           8 non-null      str
 3   Precio_Unitario  8 non-null      int64
 4   Cantidad         8 non-null      int64
 5   Sueldo           8 non-null      int64
dtypes: int64(3), str(3)
memory usage: 689.0 bytes

In [ ]:
#Devuelve filas y columanas en una tupla, (filas,colummna)

df.shape

(8, 6)

In [3]:
#Muestre una lista con los nombres de todas las colummnas
df.columns

Index(['Producto', 'Categoria', 'Region', 'Precio_Unitario', 'Cantidad',
       'Sueldo'],
      dtype='str')

In [13]:
#las 2 últimas filas
df.tail(2)

  Producto    Categoria Region  Precio_Unitario  Cantidad  Sueldo
6  Monitor  Electrónica   Este              320         2    4100
7   Laptop  Electrónica    Sur             1250         9    7500

In [ ]:
#las 2 primeras filas
df.head(2)

  Producto    Categoria Region  Precio_Unitario  Cantidad  Sueldo
0   Laptop  Electrónica  Norte             1200         2    4500
1  Teclado   Accesorios    Sur               45        10    3200

In [6]:
#FUNCIONES INDIVIDUALES FORMATO
## df['Columna'].mean()    # Promedio
## df['Columna'].median()  # Mediana (50%)
## df['Columna'].std()     # Desviación estándar
## df['Columna'].var()     # Varianza
## df['Columna'].min()     # Valor mínimo
## df['Columna'].max()     # Valor máximo
df['Cantidad'].quantile(0.90) # Percentil 90
## df['Cantidad'].sum()

np.float64(26.39999999999999)

In [7]:
df.iloc[2]

Producto                Laptop
Categoria          Electrónica
Region                   Norte
Precio_Unitario           1100
Cantidad                     1
Sueldo                    6000
Name: 2, dtype: object